package it.polimi.ingsw.Enum;

public enum CLICommands {
    CONNECT_SERVER, SET_NICKNAME, CREATE_MATCH, JOIN_MATCH_BY_TYPE,
    JOIN_MATCH_BY_ID, PLAY_CARD, MOVE_STUDENT, CHOOSE_CHARACTER, SET_CHARACTER_INPUT, DELETE_LAST_INPUT, PLAY_CHARACTER, MOVE_MOTHER_NATURE,
    MOVE_FROM_CLOUD, TEXT_MESSAGE, UNDO, QUIT
}
